name: land_photo
description: Land Photo – Glassy Social App
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

  # شبكات (لاحقًا عند ربط الـ API)
  dio: ^5.5.0+1

  # إدارة حالة خفيفة
  flutter_riverpod: ^2.5.1

  # صور/كاش
  cached_network_image: ^3.3.1

  # أنيميشن/لوتي
  lottie: ^3.1.2

  # إيموجي
  emoji_picker_flutter: ^3.1.0

  # اتصال الشبكة (بانر لا يوجد إنترنت)
  connectivity_plus: ^6.0.5

  # انتقاليّات ذكية
  go_router: ^14.2.0

  # شيمر للسكتلتون
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/like.json
    - assets/stickers/ # ضع ملصقاتك هنا (png/webp)
    - assets/emoji/    # إن رغبت بإيموجي مخصصة