name: Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # تأكيد وجود مشروع أندرويد؛ إذا ماكو android/ يتولد تلقائيًا
      - name: Ensure android folder exists
        run: |
          if [ ! -d "android" ]; then
            echo "android/ not found -> running flutter create ..."
            flutter create --platforms=android .
          else
            echo "android/ already exists"
          fi

      - name: Flutter doctor (diagnostics)
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Build APK (release, unsigned)
        run: flutter build apk --release

      - name: Upload APK (release unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-apk
          path: build/app/outputs/flutter-apk/app-release.apk
